import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useGoogleLogin } from '@react-oauth/google';
import { Loader2, ShieldCheck, CheckCircle2, Star, ArrowRight } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { useToast } from '../../context/ToastContext';
import { loginUser, adminLoginUser, googleAuth } from '../../api/auth';

const GoogleIcon = () => (
  <svg width="18" height="18" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
    <path d="M17.64 9.2c0-.637-.057-1.251-.164-1.84H9v3.481h4.844c-.209 1.125-.843 2.078-1.796 2.717v2.258h2.908c1.702-1.567 2.684-3.875 2.684-6.615z" fill="#4285F4"/>
    <path d="M9 18c2.43 0 4.467-.806 5.956-2.184l-2.908-2.258c-.806.54-1.837.86-3.048.86-2.344 0-4.328-1.584-5.036-3.711H.957v2.332C2.438 15.983 5.482 18 9 18z" fill="#34A853"/>
    <path d="M3.964 10.707A5.41 5.41 0 0 1 3.682 9c0-.593.102-1.17.282-1.707V4.961H.957A8.996 8.996 0 0 0 0 9c0 1.452.348 2.827.957 4.039l3.007-2.332z" fill="#FBBC05"/>
    <path d="M9 3.58c1.321 0 2.508.454 3.44 1.345l2.582-2.58C13.463.891 11.426 0 9 0 5.482 0 2.438 2.017.957 4.961L3.964 6.293C4.672 4.169 6.656 3.58 9 3.58z" fill="#EA4335"/>
  </svg>
);

const Login = () => {
  const { login }  = useAuth();
  const navigate   = useNavigate();
  const toast      = useToast();

  const [tab, setTab]         = useState('citizen');
  const [email, setEmail]     = useState('');
  const [password, setPassword] = useState('');
  const [error, setError]     = useState('');
  const [loading, setLoading] = useState(false);
  const [gLoading, setGLoading] = useState(false);

  const handleTabChange = (t) => {
    setTab(t);
    setError('');
    if (t === 'admin') {
      setEmail('admin@civicalign.com');
      setPassword('Admin@123');
    } else {
      setEmail('');
      setPassword('');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const apiFn = tab === 'admin' ? adminLoginUser : loginUser;
      const { access_token, user } = await apiFn({ email, password });
      login(access_token, user);
      toast.success(`Welcome back, ${user.full_name}!`);
      navigate(tab === 'admin' ? '/admin/dashboard' : '/dashboard');
    } catch (err) {
      setError(err.response?.data?.error || 'Invalid email or password');
    } finally {
      setLoading(false);
    }
  };

  const triggerGoogleLogin = useGoogleLogin({
    onSuccess: async (tokenResponse) => {
      setGLoading(true);
      setError('');
      try {
        const { access_token: jwt, user } = await googleAuth(tokenResponse.access_token);
        login(jwt, user);
        toast.success(`Welcome, ${user.full_name}!`);
        navigate('/dashboard');
      } catch (err) {
        const msg = err?.response?.data?.error || 'Google sign-in failed. Please try again.';
        setError(msg);
      } finally {
        setGLoading(false);
      }
    },
    onError: () => setError('Google sign-in was cancelled or failed.'),
  });

  const anyLoading = loading || gLoading;

  return (
    <div className="min-h-screen grid grid-cols-1 lg:grid-cols-12 page-fade">
      
      {/* Left panel: Info screen */}
      <div className="hidden lg:flex lg:col-span-5 bg-[#1A3A6B] flex-col justify-between p-12 text-white relative overflow-hidden">
        {/* Background mesh glow */}
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(15,123,108,0.25),transparent_45%)]" />
        
        {/* Top: Logo branding */}
        <div className="flex items-center gap-2.5 z-10">
          <ShieldCheck size={28} className="text-[#F5A623]" />
          <div>
            <span className="text-2xl font-extrabold tracking-tight font-poppins text-white">Civic</span>
            <span className="text-2xl font-extrabold tracking-tight font-poppins text-blue-300">Align</span>
          </div>
        </div>

        {/* Center: Highlight items */}
        <div className="space-y-8 z-10 my-auto">
          <div>
            <h1 className="text-3xl font-extrabold tracking-tight leading-tight font-poppins">
              CivicAlign
            </h1>
            <p className="text-slate-300 mt-2 text-sm leading-relaxed">
              Empowering citizens and municipal administrators through collaborative, agent-audited public issue resolution.
            </p>
          </div>

          <div className="space-y-4">
            {[
              {
                title: 'AI-Audited Evidence Verification',
                desc: 'Upload images to analyze issue severity, trust status, and geographical coordinates automatically.',
              },
              {
                title: 'Multi-Agent Reasoning Trace',
                desc: 'Inspect background actions and planning audits generated by specialized AI agents transparently.',
              },
              {
                title: 'Civic Leaderboard & Initiatives',
                desc: 'Earn civic points, unlock rewards badges, and cluster local complaints into coordinated development plans.',
              },
            ].map((item, idx) => (
              <div key={idx} className="flex gap-3">
                <CheckCircle2 size={18} className="text-[#0F7B6C] shrink-0 mt-0.5" />
                <div>
                  <h3 className="font-bold text-sm text-white">{item.title}</h3>
                  <p className="text-slate-300 text-xs mt-1 leading-relaxed">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Bottom: Submission footer */}
        <div className="z-10 text-slate-400 text-xs flex items-center gap-1.5 font-semibold uppercase tracking-wider">
          <span>© {new Date().getFullYear()} CivicAlign. All rights reserved.</span>
        </div>
      </div>

      {/* Right panel: Form container */}
      <div className="col-span-12 lg:col-span-7 flex items-center justify-center p-6 sm:p-12 bg-[#F4F6FA]">
        <div className="max-w-md w-full bg-white p-8 rounded-2xl shadow-[0_4px_20px_rgba(0,0,0,0.06)] border border-gray-100 space-y-6">
          
          {/* Header */}
          <div className="text-center">
            <h2 className="text-2xl font-extrabold text-[#1A1A2E] font-poppins">Sign In to CivicAlign</h2>
            <p className="mt-2 text-sm text-[#5A6A7A]">
              Don't have an account?{' '}
              <Link to="/register" className="font-bold text-[#1A3A6B] hover:underline">
                Register here
              </Link>
            </p>
          </div>

          {/* Citizen / Admin tab bar */}
          <div className="flex bg-[#F4F6FA] p-1.5 rounded-xl border border-[#DDE3ED]">
            {['citizen', 'admin'].map((t) => (
              <button
                key={t}
                type="button"
                onClick={() => handleTabChange(t)}
                className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all ${
                  tab === t
                    ? 'bg-white text-[#1A3A6B] shadow-sm'
                    : 'text-[#5A6A7A] hover:text-[#1A1A2E]'
                }`}
              >
                {t === 'citizen' ? 'Citizen' : 'Administrator'}
              </button>
            ))}
          </div>

          {/* Demo Admin credentials notice */}
          {tab === 'admin' && (
            <div className="bg-[#1A3A6B]/5 border border-[#1A3A6B]/20 text-[#1A1A2E] rounded-xl p-4 text-xs space-y-1.5">
              <div className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[10px] text-[#1A3A6B]">
                <ShieldCheck size={12} /> Demo Admin Credentials
              </div>
              <div className="text-[#5A6A7A]">
                <div><strong>Email:</strong> <span className="font-mono text-gray-800 selection:bg-blue-100">admin@civicalign.com</span></div>
                <div className="mt-0.5"><strong>Password:</strong> <span className="font-mono text-gray-800 selection:bg-blue-100">Admin@123</span></div>
              </div>
            </div>
          )}

          {/* Error Message */}
          {error && (
            <div className="bg-red-50 border border-red-200 text-[#C0392B] text-sm px-4 py-3 rounded-xl font-medium">
              {error}
            </div>
          )}

          {/* Google SSO Login */}
          {tab === 'citizen' && (
            <>
              <button
                type="button"
                onClick={() => triggerGoogleLogin()}
                disabled={anyLoading}
                className="w-full flex items-center justify-center gap-3 px-4 py-2.5 border border-[#DDE3ED] rounded-xl bg-white text-sm font-bold text-gray-700 hover:bg-gray-50 hover:border-gray-400 disabled:opacity-60 disabled:cursor-not-allowed transition-all shadow-sm"
              >
                {gLoading ? (
                  <Loader2 size={18} className="animate-spin text-gray-400" />
                ) : (
                  <GoogleIcon />
                )}
                {gLoading ? 'Connecting to Google…' : 'Continue with Google'}
              </button>

              {/* Divider */}
              <div className="flex items-center gap-3 py-1">
                <hr className="flex-1 border-[#DDE3ED]" />
                <span className="text-[11px] text-[#5A6A7A] font-bold uppercase tracking-wider">or email access</span>
                <hr className="flex-1 border-[#DDE3ED]" />
              </div>
            </>
          )}

          {/* Login Form */}
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-xs font-bold text-[#5A6A7A] uppercase tracking-wider mb-1.5">Email Address</label>
              <input
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="gov-input"
                placeholder="you@example.gov"
                autoComplete="email"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-[#5A6A7A] uppercase tracking-wider mb-1.5">Password</label>
              <input
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="gov-input"
                placeholder="••••••••"
                autoComplete="current-password"
              />
            </div>

            <div className="flex justify-end pt-1">
              <Link
                to="/forgot-password"
                className="text-xs font-bold text-[#1A3A6B] hover:underline"
              >
                Forgot password?
              </Link>
            </div>

            <button
              type="submit"
              disabled={anyLoading}
              className="gov-btn-primary w-full h-11 text-sm font-bold mt-2"
            >
              {loading && <Loader2 size={16} className="animate-spin" />}
              {loading
                ? 'Verifying Session…'
                : tab === 'admin'
                ? 'Sign in as Administrator'
                : 'Sign in with Email'}
            </button>
          </form>

        </div>
      </div>

    </div>
  );
};

export default Login;
